spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
        routes:
        - id: CARDSERVICE
          uri: lb://card-service
          predicates:
            - Path=/card/**
        - id: CARDTYPESERVICE
          uri: lb://card-type-service
          predicates:
            - Path=/card-type/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

