spring:
  application:
    name: company-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    username: root
    password: password
    url: ${DATABASE_URL_COMPANY_SERVICE:jdbc:postgresql://localhost:5432/company_service}
  flyway:
    enabled: true
#  mvc:
#    problemdetails:
#      enabled: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8082/eureka/}

server:
  port: 8085

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework:
        web: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true