spring:
  application:
    name: company-service
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    username: root
    password: password
    url: ${DATABASE_URL_COMPANY_SERVICE:jdbc:postgresql://localhost:5432/company_service}
  flyway:
    enabled: true
#  mvc:
#    problemdetails:
#      enabled: true