spring:
  application:
    name: discovery-server-service

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #Eureka cannot register itself as a client.
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
